name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v0.9.0.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run docker build
        run: |
          docker build -f docker/Dockerfile.cpu --tag ${{ secrets.DOCKER_USERNAME }}/vllm-cpu --target vllm-openai .
          docker login  --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_USERNAME }}/vllm-cpu
